'use client';
import {useEffect,useState} from 'react';
import Invitation from './invitation';
import {Choice,download} from './ui';
import {toast,Toaster} from 'sonner';
import {Button} from '@/components/ui/button';
import {uploadFile} from '@/lib/upload-client';
export default function GuestView({token}:{token:string}){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[form,setForm]=useState<any>({responses:{}}),[photos,setPhotos]=useState<any[]>([]),[secondary,setSecondary]=useState(false),[busy,setBusy]=useState(false),[success,setSuccess]=useState(false);
useEffect(()=>{fetch('/api/guest?token='+encodeURIComponent(token)).then(async r=>{const d=(await r.json() as any);if(!r.ok)throw Error(d.error);setData(d);setForm({...d.guest,bringPlusOne:!!d.guest.plusOneName});}).catch(e=>setError(e.message));fetch('/api/photos?token='+encodeURIComponent(token)).then(r=>r.json() as Promise<any>).then(d=>setPhotos(d.photos||[]));},[token]);
const field=(k:string,v:any)=>setForm({...form,[k]:v});const label=(key:string,fallback:string)=>secondary?(data?.settings.secondary?.[key]||fallback):fallback;
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/guest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,token})});const d=(await r.json() as any);if(!r.ok)throw Error(d.error);setForm((f:any)=>({...f,...d.guest}));setData((current:any)=>({...current,guest:{...current.guest,...d.guest}}));setSuccess(true);toast.success('Your RSVP is saved');}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
async function upload(files:FileList|null){if(!files)return;setBusy(true);try{for(const file of Array.from(files)){await uploadFile(file,{token,kind:'photo'});}toast.success('Thank you for sharing your photos');const r=await fetch('/api/photos?token='+encodeURIComponent(token));setPhotos(((await r.json() as any)).photos||[]);}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
function calendar(){const esc=(x:string)=>x.replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(',','\\,').replaceAll(';','\\;');const items=data.events.map((e:any)=>['BEGIN:VEVENT','UID:'+e.id+'@our-wedding','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').split('.')[0]+'Z','DTSTART:'+e.date.replaceAll('-','')+'T'+e.time.replace(':','')+'00','SUMMARY:'+esc(e.name),'LOCATION:'+esc(e.venue),'END:VEVENT'].join('\r\n'));download('wedding-weekend.ics',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Our Wedding//EN',...items,'END:VCALENDAR'].join('\r\n'),'text/calendar')}
if(error)return <main className="guest-error"><h1>Your private invitation</h1><p>{error}</p><Button onClick={()=>location.reload()}>Try again</Button></main>;
if(!data)return <main className="guest-error"><h1>Something beautiful is coming.</h1><p>Opening your invitation…</p></main>;
const attending=Object.values(form.responses||{}).includes('yes');return <main className="guest-page"><Toaster richColors/><div className="guest-top"><span>For {data.guest.name}</span>{data.settings.language&&<Button variant="outline" onClick={()=>setSecondary(!secondary)}>{secondary?'English':data.settings.language}</Button>}</div><Invitation settings={data.settings} events={data.events} story={data.story} token={token} secondary={secondary}>
{data.guest.plusOneAllowed&&<section className="invite-section plus-one-note"><span className="eyebrow">{label('plusOneWelcomeLabel','A little extra company')}</span><h2>{label('plusOneWelcome','You are welcome to bring a plus-one.')}</h2><p>{label('plusOneInstructions','If you’re bringing someone, add their name and details when you RSVP below.')}</p></section>}
<section className="invite-section"><Button variant="outline" onClick={calendar}>{label('calendarLabel','Add the weekend to my calendar')}</Button></section>
<section className="invite-section" id="rsvp"><span className="eyebrow">RSVP</span><h2>{label('rsvpTitle','Will you celebrate with us?')}</h2><p>{label('deadlineLabel','Please reply by')} {data.settings.rsvpDeadline}</p>{success&&<div className="success"><strong>{label('thankYou','Thank you, your reply is saved.')}</strong><p>{label('updateReply','You can update it at any time using this link.')}</p><Button variant="outline" onClick={()=>download('my-rsvp.txt',data.guest.name+'\n'+data.events.map((e:any)=>e.name+': '+(form.responses?.[e.id]==='yes'?'Attending':'Not attending')).join('\n')+'\nMeal: '+form.meal)}>Download my confirmation</Button></div>}
<form onSubmit={submit} className={"rsvp-form text-"+(data.settings.rsvpTextSize||"Standard").toLowerCase()}><fieldset><legend>{label('yourDetailsLabel','Your details')}</legend><label>{label('fullNameLabel','Your full name')}<input autoComplete="name" required maxLength={150} value={form.name||''} onChange={e=>field('name',e.target.value)}/></label><label>{label('phoneLabel','Phone number')}<input type="tel" autoComplete="tel" maxLength={50} value={form.phone||''} onChange={e=>field('phone',e.target.value)}/></label></fieldset>{data.events.map((e:any)=><label key={e.id}>{secondary&&e.secondaryName?e.secondaryName:e.name}<Choice value={form.responses?.[e.id]||''} label={label('attendanceLabel','Your attendance')} options={[{value:'yes',label:label('acceptLabel','Joyfully accepts')},{value:'no',label:label('declineLabel','Regretfully declines')}]} onChange={v=>field('responses',{...form.responses,[e.id]:v})}/></label>)}
{attending&&<><label>{label('mealLabel','Your meal')}<Choice value={form.meal||''} onChange={v=>field('meal',v)} options={String(data.settings.mealOptions).split(',').map((x:string)=>x.trim())}/></label><label>{label('allergyLabel','Allergies or dietary requirements')}<textarea value={form.allergy||''} onChange={e=>field('allergy',e.target.value)}/></label>{data.guest.plusOneAllowed&&<fieldset className="plus-one-fields"><legend>{label('plusOneDetailsLabel','Your plus-one')}</legend><p>{label('plusOneWelcome','You are welcome to bring a plus-one.')}</p><label>{label('bringingPlusOneLabel','Will you bring a plus-one?')}<Choice value={form.bringPlusOne?'yes':'no'} options={[{value:'no',label:label('comingAloneLabel','I’m coming on my own')},{value:'yes',label:label('bringingCompanionLabel','Yes, I’m bringing someone')}]} onChange={v=>setForm({...form,bringPlusOne:v==='yes',...(v==='no'?{plusOneName:'',plusOneMeal:'',plusOneAllergy:'',plusOnePhone:''}:{})})}/></label>{form.bringPlusOne&&<><label>{label('plusOneNameLabel','Plus-one’s full name')}<input required maxLength={150} autoComplete="off" value={form.plusOneName||''} onChange={e=>field('plusOneName',e.target.value)}/></label><label>{label('plusPhoneLabel','Plus-one phone number (optional)')}<input type="tel" autoComplete="off" maxLength={50} value={form.plusOnePhone||''} onChange={e=>field('plusOnePhone',e.target.value)}/></label><label>{label('plusMealLabel','Plus-one meal')}<Choice value={form.plusOneMeal||''} options={String(data.settings.mealOptions).split(',').map((x:string)=>x.trim())} onChange={v=>field('plusOneMeal',v)}/></label><label>{label('plusAllergyLabel','Plus-one dietary requirements')}<textarea value={form.plusOneAllergy||''} onChange={e=>field('plusOneAllergy',e.target.value)}/></label></>}</fieldset>}<label>{label('songLabel','A song to get you dancing')}<input value={form.song||''} onChange={e=>field('song',e.target.value)}/></label></>}
<label>{data.settings.rsvpQuestion||label('messageLabel','A little note for us')}<textarea value={form.message||''} onChange={e=>field('message',e.target.value)}/></label><Button disabled={busy} type="submit">{busy?label('savingLabel','Saving…'):label('saveRsvpLabel','Save my RSVP')}</Button></form></section>
<section className="invite-section"><span className="eyebrow">{label('photosLabel','Through your eyes')}</span><h2>{label('photoTitle','Share a little of the magic.')}</h2><p>{label('photoDescription','Upload your favourite photos from our celebration.')}</p><label className="upload-button">{busy?'Uploading…':label('uploadLabel','Choose photos')}<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>upload(e.target.files)}/></label>{data.settings.photoWall&&<div className="photo-grid">{photos.filter(p=>p.mime?.startsWith('image/')).map(p=><figure key={p.id}><a href={'/api/media/'+p.id+'?token='+encodeURIComponent(token)} target="_blank" rel="noreferrer"><img src={'/api/media/'+p.id+'?token='+encodeURIComponent(token)} alt={'Wedding photo by '+p.name}/></a><figcaption>{p.name}</figcaption></figure>)}</div>}</section>
</Invitation></main>}
