'use client';
import {dateText} from './ui';
import {safeUrl} from '@/lib/model';
import {BackgroundMusic,LoopingVideo} from './invitation-media';
export default function Invitation({settings:s,events,story=[],token,children,secondary=false}:{settings:any;events:any[];story?:any[];token?:string;children?:React.ReactNode;secondary?:boolean}){const text=(k:string)=>secondary&&s.secondary?.[k]?s.secondary[k]:s[k];const asset=(u:string)=>safeUrl(u)+(u?.startsWith('/api/media/')&&token?'?token='+encodeURIComponent(token):'');return <div className={'invitation theme-'+s.theme} style={{'--invite-accent':s.accent} as any}>
<div className="invite-opening"><span className="eyebrow">{secondary?(s.secondary?.inviteLabel||'You are invited'):'Together with our favourite people'}</span><h1>{text('names')}</h1><div className="fine-rule"/><p className="invite-welcome">{text('welcome')}</p><p>{dateText(s.date)}</p><span className="eyebrow">{text('venue')}</span></div>
{safeUrl(s.video)&&<LoopingVideo src={asset(s.video)}/>}{safeUrl(s.cover)&&<img className="invite-art" src={asset(s.cover)} alt="Wedding invitation artwork"/>}
<div className="invite-section"><span className="eyebrow">{secondary?(s.secondary?.celebrationLabel||'Our celebration'):'Our celebration'}</span><h2>{text('message')}</h2><p>{text('dress')}</p></div>
<div className="invite-section schedule"><span className="eyebrow">{secondary?(s.secondary?.weekendLabel||'The wedding weekend'):'The wedding weekend'}</span>{events.map(e=><div key={e.id} className="schedule-item"><div><strong>{e.time}</strong><small>{dateText(e.date)}</small></div><div><h3>{secondary&&e.secondaryName?e.secondaryName:e.name}</h3><p>{secondary&&e.secondaryDescription?e.secondaryDescription:e.description}</p><small>{e.venue}</small></div></div>)}</div>
<div className="invite-section"><span className="eyebrow">{secondary?(s.secondary?.detailsLabel||'The little details'):'The little details'}</span><h2>{text('venue')}</h2><p>{text('address')}</p>{/^https?:\/\//.test(s.map||'')&&<a className="button" href={s.map} target="_blank" rel="noreferrer">{secondary?(s.secondary?.directionsLabel||'Get directions'):'Get directions'}</a>}<h3>{secondary?(s.secondary?.travelLabel||'Travel & accommodation'):'Travel & accommodation'}</h3><p className="preserve">{text('travel')}</p></div>
{!!story.length&&<div className="invite-section"><span className="eyebrow">{secondary?(s.secondary?.storyLabel||'Our story'):'Our story'}</span>{story.map(x=><article className="story-item" key={x.id}>{safeUrl(x.image)&&<img src={asset(x.image)} alt={x.name}/>}<h3>{secondary&&x.secondaryName?x.secondaryName:x.name}</h3><p>{secondary&&x.secondaryNotes?x.secondaryNotes:x.notes}</p></article>)}</div>}
{(s.banking||s.registry)&&<div className="invite-section"><span className="eyebrow">{secondary?(s.secondary?.giftsLabel||'Gifts'):'Gifts'}</span><p>{secondary?(s.secondary?.giftMessage||'Your presence means the world to us.'):'Your presence means the world to us. If you would like to give a gift, here are the details.'}</p><p className="preserve">{text('banking')}</p>{/^https?:\/\//.test(s.registry||'')&&<a className="button" href={s.registry} target="_blank" rel="noreferrer">{secondary?(s.secondary?.registryLabel||'View our registry'):'View our registry'}</a>}</div>}
{safeUrl(s.music)&&<BackgroundMusic src={asset(s.music)}/>}
{children}<footer className="invite-footer">{text('names')} · {dateText(s.date)}</footer></div>}
