'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {BedDouble,Plus,Car} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Choice} from '../ui';
import {roomUsage} from '@/lib/hub';
import {uid,type Wedding,type RecordItem} from '@/lib/model';
import type {Save,HubData} from './common';
export default function StayView({w,save,hub}:{w:Wedding;save:Save;hub:HubData}){
 const [room,setRoom]=useState<RecordItem|null>(null),[alloc,setAlloc]=useState<RecordItem|null>(null),[note,setNote]=useState({accommodationNote:w.settings.accommodationNote||'',travelNote:w.settings.travelNote||''});
 const usage=roomUsage(w),states=hub?.states||{},name=(id:string)=>w.guests.find(g=>g.id===id)?.name||'Guest';
 const requests=w.guests.filter(g=>states[g.id]?.accommodation?.wanted==='yes');
 const unallocated=requests.filter(g=>!w.allocations.some(a=>a.guestId===g.id));
 const free=(roomId:string,except?:string)=>{const u=usage.get(roomId);if(!u)return 0;const mine=w.allocations.find(a=>a.id===except&&a.roomId===roomId);return u.capacity-u.confirmed-u.pending+(mine?Number(mine.people)||1:0);};
 async function saveAlloc(a:RecordItem){const people=Number(a.people)||1;if(!a.roomId){toast.error('Choose a room.');return;}if(people>free(a.roomId,a.isNew?undefined:a.id)){toast.error(`Only ${Math.max(0,free(a.roomId,a.isNew?undefined:a.id))} bed(s) free in that room.`);return;}
  const {isNew,...clean}=a;const next={...w,allocations:isNew?[...w.allocations,{...clean,people,updatedAt:new Date().toISOString()}]:w.allocations.map(x=>x.id===a.id?{...clean,people,updatedAt:new Date().toISOString()}:x)};if(await save(next)){setAlloc(null);toast.success(a.status==='confirmed'?'Room confirmed — the guest sees it on their page':'Room held (pending) — the guest sees it as awaiting confirmation');}}
 return <>
  <section className="panel"><div className="panel-heading"><h2>What guests see</h2></div>
   <label className="toggle"><Switch checked={!!w.settings.accommodationOffered} onCheckedChange={v=>save({...w,settings:{...w.settings,accommodationOffered:v}})}/> Ask attending guests whether they need accommodation</label>
   <label className="toggle"><Switch checked={w.settings.travelQuestions!==false} onCheckedChange={v=>save({...w,settings:{...w.settings,travelQuestions:v}})}/> Ask attending guests for travel dates, transport needs and lifts</label>
   <form className="edit-form" onSubmit={async e=>{e.preventDefault();if(await save({...w,settings:{...w.settings,...note}}))toast.success('Saved');}}><label>Accommodation note for guests<textarea value={note.accommodationNote} onChange={e=>setNote({...note,accommodationNote:e.target.value})}/></label><label>Travel note for guests<textarea value={note.travelNote} onChange={e=>setNote({...note,travelNote:e.target.value})}/></label><Button type="submit" variant="outline">Save notes</Button></form></section>
  <section className="panel"><div className="panel-heading"><h2><BedDouble size={18}/> Rooms &amp; capacity</h2><Button onClick={()=>setRoom({id:uid(),isNew:true,name:'',place:'',capacity:2,guestNotes:'',notes:''})}><Plus size={15}/> Add room</Button></div>
   {!w.rooms.length&&<p className="muted">Add the rooms, cottages or hotel blocks you can offer. Each has a number of beds; held and confirmed allocations can never exceed it.</p>}
   <div className="room-grid">{w.rooms.map(r=>{const u=usage.get(r.id)!;return <div className="room-card" key={r.id}><div className="panel-heading"><div><h3>{r.name}</h3><small className="muted">{r.place}</small></div><Button variant="ghost" size="sm" onClick={()=>setRoom({...r})}>Edit</Button></div>
    <div className="capacity" aria-label={`${u.confirmed} confirmed, ${u.pending} held, ${u.capacity-u.confirmed-u.pending} free`}><i className="confirmed" style={{width:`${u.confirmed/u.capacity*100}%`}}/><i className="held" style={{width:`${u.pending/u.capacity*100}%`}}/></div>
    <small>{u.confirmed} confirmed · {u.pending} held · <strong>{u.capacity-u.confirmed-u.pending} free</strong> of {u.capacity}</small>
    <ul className="alloc-list">{w.allocations.filter(a=>a.roomId===r.id).map(a=><li key={a.id}><span>{name(a.guestId)} · {a.people} {Number(a.people)===1?'person':'people'}{a.from?` · ${a.from} – ${a.to||'?'}`:''}</span><span className={'badge '+(a.status==='confirmed'?'yes':'')}>{a.status==='confirmed'?'Confirmed':'Held'}</span><Button variant="ghost" size="sm" onClick={()=>setAlloc({...a})}>Change</Button></li>)}</ul></div>;})}</div></section>
  <section className="panel"><div className="panel-heading"><h2>Requests from guests</h2><span className="badge">{unallocated.length} waiting</span></div>
   {!requests.length&&<p className="muted">No accommodation requests yet.</p>}
   {!!requests.length&&<div className="table-scroll"><Table><TableHeader><TableRow>{['Guest','People','Dates','Notes','Status',''].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{requests.map(g=>{const rq=states[g.id].accommodation,a=w.allocations.find(x=>x.guestId===g.id);return <TableRow key={g.id}><TableCell><strong>{g.name}</strong></TableCell><TableCell>{rq.people||1}</TableCell><TableCell>{rq.from||'?'} – {rq.to||'?'}</TableCell><TableCell className="small">{rq.notes}</TableCell><TableCell>{a?<span className={'badge '+(a.status==='confirmed'?'yes':'')}>{a.status==='confirmed'?'Confirmed':'Held · pending'}</span>:<span className="badge">Requested</span>}</TableCell>
    <TableCell>{a?<Button variant="outline" size="sm" onClick={()=>setAlloc({...a})}>Change</Button>:<Button size="sm" disabled={!w.rooms.length} onClick={()=>setAlloc({id:uid(),isNew:true,guestId:g.id,roomId:'',people:rq.people||1,from:rq.from||'',to:rq.to||'',status:'pending'})}>Allocate</Button>}</TableCell></TableRow>;})}</TableBody></Table></div>}</section>
  <section className="panel"><div className="panel-heading"><h2><Car size={18}/> Travel &amp; lifts</h2></div>
   {!w.guests.some(g=>states[g.id]?.travel||states[g.id]?.lift)&&<p className="muted">Guests’ travel dates, transport needs and lift offers will appear here.</p>}
   {w.guests.some(g=>states[g.id]?.travel||states[g.id]?.lift)&&<div className="table-scroll"><Table><TableHeader><TableRow>{['Guest','Arrives','Leaves','Transport','Lift'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{w.guests.filter(g=>states[g.id]?.travel||(states[g.id]?.lift&&states[g.id].lift.mode!=='none')).map(g=>{const t=states[g.id].travel||{},l=states[g.id].lift;return <TableRow key={g.id}><TableCell><strong>{g.name}</strong></TableCell><TableCell>{t.arrive||'—'}</TableCell><TableCell>{t.depart||'—'}</TableCell><TableCell className="small">{[t.transport,t.notes].filter(Boolean).join(' · ')||'—'}</TableCell><TableCell className="small">{l&&l.mode!=='none'?`${l.mode==='offer'?`Offers ${l.seats} seat(s)`:'Needs a lift'}${l.from?` from ${l.from}`:''} · ${l.share?'sharing with guests':'private to us'}`:'—'}</TableCell></TableRow>;})}</TableBody></Table></div>}</section>
  <Dialog open={!!room} onOpenChange={v=>!v&&setRoom(null)}><DialogContent className="edit-dialog">{room&&<><DialogHeader><DialogTitle>{room.isNew?'Add room':'Edit room'}</DialogTitle><DialogDescription>Capacity is the number of people (beds) for the weekend.</DialogDescription></DialogHeader>
   <form className="edit-form" onSubmit={async e=>{e.preventDefault();const u=usage.get(room.id);if(u&&Number(room.capacity)<u.confirmed+u.pending){toast.error(`${u.confirmed+u.pending} people are already allocated to this room.`);return;}const {isNew,...r}:RecordItem={...room,capacity:Number(room.capacity)};if(await save({...w,rooms:isNew?[...w.rooms,r]:w.rooms.map(x=>x.id===r.id?r:x)})){setRoom(null);toast.success('Room saved');}}}>
    <label>Name<input required value={room.name} onChange={e=>setRoom({...room,name:e.target.value})}/></label><label>Where<input value={room.place} onChange={e=>setRoom({...room,place:e.target.value})}/></label>
    <label>Beds (people)<input type="number" min={1} required value={room.capacity} onChange={e=>setRoom({...room,capacity:e.target.value})}/></label>
    <label>Note shown to guests allocated here<textarea value={room.guestNotes||''} onChange={e=>setRoom({...room,guestNotes:e.target.value})}/></label><label>Private notes<textarea value={room.notes||''} onChange={e=>setRoom({...room,notes:e.target.value})}/></label>
    <div className="toolbar"><Button type="submit">Save room</Button>{!room.isNew&&<Button type="button" variant="ghost" onClick={async()=>{if(w.allocations.some(a=>a.roomId===room.id)){toast.error('Move or release this room’s guests first.');return;}if(confirm('Delete this room?')&&await save({...w,rooms:w.rooms.filter(x=>x.id!==room.id)}))setRoom(null);}}>Delete</Button>}</div></form></>}</DialogContent></Dialog>
  <Dialog open={!!alloc} onOpenChange={v=>!v&&setAlloc(null)}><DialogContent className="edit-dialog">{alloc&&<><DialogHeader><DialogTitle>Accommodation for {name(alloc.guestId)}</DialogTitle><DialogDescription>Held rooms show as “awaiting confirmation” to the guest; confirmed rooms show the room details.</DialogDescription></DialogHeader>
   <form className="edit-form" onSubmit={e=>{e.preventDefault();saveAlloc(alloc);}}>
    <label>Room<Choice value={alloc.roomId} label="Choose a room" options={w.rooms.map(r=>({value:r.id,label:`${r.name} · ${free(r.id,alloc.isNew?undefined:alloc.id)} free`}))} onChange={v=>setAlloc({...alloc,roomId:v})}/></label>
    <label>People<input type="number" min={1} value={alloc.people} onChange={e=>setAlloc({...alloc,people:e.target.value})}/></label>
    <div className="two-col"><label>From<input type="date" value={alloc.from||''} onChange={e=>setAlloc({...alloc,from:e.target.value})}/></label><label>To<input type="date" value={alloc.to||''} onChange={e=>setAlloc({...alloc,to:e.target.value})}/></label></div>
    <label>Status<Choice value={alloc.status} options={[{value:'pending',label:'Held — awaiting confirmation'},{value:'confirmed',label:'Confirmed booking'}]} onChange={v=>setAlloc({...alloc,status:v})}/></label>
    <div className="toolbar"><Button type="submit">Save</Button>{!alloc.isNew&&<Button type="button" variant="ghost" onClick={async()=>{if(confirm('Release this room? The guest will see their request as waiting again.')&&await save({...w,allocations:w.allocations.filter(a=>a.id!==alloc.id)})){setAlloc(null);toast.success('Released');}}}>Release room</Button>}</div></form></>}</DialogContent></Dialog>
 </>;
}
