export type RecordItem = {id:string;[key:string]:any};
export type Wedding = { settings:Record<string,any>; events:RecordItem[]; guests:RecordItem[]; tables:RecordItem[]; budget:RecordItem[]; vendors:RecordItem[]; tasks:RecordItem[]; moodboard:RecordItem[]; story:RecordItem[]; gifts:RecordItem[]; layout:RecordItem[] };
export const sections = ['settings','events','guests','tables','budget','vendors','tasks','moodboard','story','gifts','layout'] as const;
export const uid=()=>crypto.randomUUID();
export function initialWedding():Wedding {return {
 settings:{names:'Mienke & Luvhan',date:'2027-04-24',venue:'Our wedding venue',address:'Venue details coming soon',map:'',welcome:'A little piece of Greece. A lifetime together.',message:'We cannot wait to celebrate with our favourite people.',dress:'Coastal elegance',travel:'Accommodation and travel details will be added here.',theme:'aegean',accent:'#174d8c',cover:'/coast.png',music:'',language:'Afrikaans',photoWall:true,mealOptions:'Standard,Vegetarian,Vegan',budget:80000,catering:0,banking:'',registry:'',rsvpDeadline:'2027-03-24',secondary:{}},
 events:[{id:'welcome',name:'Welcome gathering',date:'2027-04-23',time:'17:00',venue:'Details to follow',description:'A relaxed start to our wedding weekend.'},{id:'ceremony',name:'The wedding',date:'2027-04-24',time:'15:00',venue:'Details to follow',description:'The moment we say I do.'},{id:'brunch',name:'Farewell brunch',date:'2027-04-25',time:'10:00',venue:'Details to follow',description:'One last coffee, one more hug.'}],
 layout:[{id:uid(),name:'Dance floor',event:'ceremony',x:35,y:65},{id:uid(),name:'Bar',event:'ceremony',x:80,y:5},{id:uid(),name:'DJ booth',event:'ceremony',x:80,y:85},{id:uid(),name:'Entrance',event:'ceremony',x:3,y:85}],guests:[],tables:[],budget:[],vendors:[],moodboard:[],story:[],gifts:[],tasks:[{id:uid(),name:'Confirm the venue and accommodation',category:'Venue',due:'2026-11-01',priority:'High',done:false},{id:uid(),name:'Add guests and send invitations',category:'Guests',due:'2027-01-24',priority:'High',done:false},{id:uid(),name:'Choose the menu with our caterer',category:'Food',due:'2027-02-24',priority:'Normal',done:false},{id:uid(),name:'Finalise table arrangements',category:'Guests',due:'2027-04-10',priority:'High',done:false}]};}
export function attending(g:RecordItem,event?:string){return event?g.responses?.[event]==='yes':Object.values(g.responses||{}).includes('yes');}
export function countGuests(w:Wedding,event?:string){return w.guests.filter(g=>attending(g,event)).reduce((n,g)=>n+1+(g.plusOneName?1:0),0);}
export function safeUrl(url:string){if(typeof url!=='string')return '';return /^https?:\/\//i.test(url)||url.startsWith('/api/media/')||url==='/coast.png'?url:'';}
export function totals(w:Wedding){const catering=countGuests(w)*Number(w.settings.catering||0);const estimated=w.budget.reduce((n,b)=>n+Number(b.actual||b.estimated||0),0)+catering;const paid=w.budget.reduce((n,b)=>n+(b.payments||[]).reduce((m:number,p:any)=>m+Number(p.amount||0),0),0);return {estimated,paid,catering,remaining:estimated-paid};}
