import { getCoupleUser } from './auth';
import { initialWedding, type Wedding, sections } from './model';
import { dataStore, mutateJSON, ifUnchanged } from './store';
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export type WeddingRow={owner:string;revision:number;w:Wedding;etag:string};
export type PhotoRecord={id:string;guest:string;name:string;mime:string;kind:'photo'|'asset';created:string};
export async function row():Promise<WeddingRow|null>{const r=await dataStore().getWithMetadata('wedding',{type:'json'});if(!r?.data)return null;return {...(r.data as Omit<WeddingRow,'etag'>),etag:r.etag||''};}
export async function planner(req?:Request){const user=await getCoupleUser(req);if(!user)throw new HttpError(401,'Please sign in to your wedding dashboard.');let r=await row();if(!r){await dataStore().setJSON('wedding',{owner:'couple',revision:0,w:initialWedding()},{onlyIfNew:true});r=await row();}if(!r)throw new HttpError(503,'Wedding storage is temporarily unavailable. Please try again.');if(r.owner!=='couple')throw new HttpError(503,'Import this wedding using the transfer tool before opening the planner.');return {r,user,w:r.w,owner:r.owner===user.userId};}
export async function guest(token:string){if(!token||token.length>100)throw new HttpError(403,'This invitation link is not valid.');const r=await row();if(!r)throw new HttpError(404,'The invitation is not ready yet.');const w=r.w;const g=w.guests.find(g=>g.token===token);if(!g)throw new HttpError(403,'This invitation link is not valid. Please ask the couple for your link.');return {r,w,g};}
// Saves only if nobody else saved since `r` was read (ETag check), so concurrent RSVPs are never lost.
export async function update(r:WeddingRow,w:Wedding){const result=await dataStore().setJSON('wedding',{owner:r.owner,revision:r.revision+1,w},ifUnchanged(r.etag));if(!result.modified)throw new HttpError(409,'Someone else just updated the wedding. Reload before saving again.');return r.revision+1;}
export function failure(e:unknown){console.error(e);return Response.json({error:e instanceof Error?e.message:'Unable to save. Please try again.'},{status:e instanceof HttpError?e.status:503});}
export function checkOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new HttpError(403,'Invalid request origin.');}
export function validate(w:any):asserts w is Wedding {if(!w||typeof w.settings!=='object')throw new HttpError(400,'Invalid wedding details.');for(const key of sections.slice(1)){if(!Array.isArray(w[key])||w[key].length>5000)throw new HttpError(400,'Invalid wedding records.');for(const item of w[key]){if(typeof item.id!=='string')throw new HttpError(400,'Each record needs an identifier.');}}for(const g of w.guests){if(typeof g.name!=='string'||!g.name.trim()||typeof g.token!=='string'||g.token.length<20)throw new HttpError(400,'Each guest needs a name and a secure invitation link.');}for(const g of w.guests){delete g.email;delete g.plusOneEmail;if(!g.plusOneAllowed){for(const key of ['plusOneName','plusOneMeal','plusOneAllergy','plusOnePhone'])g[key]='';}}const guestIds=new Set(w.guests.map((g:any)=>g.id));if(guestIds.size!==w.guests.length||new Set(w.guests.map((g:any)=>g.token)).size!==w.guests.length)throw new HttpError(400,'Guest identifiers must be unique.');for(const t of w.tables){if(!Number.isInteger(Number(t.capacity))||Number(t.capacity)<1)throw new HttpError(400,'Table capacities must be positive.');t.assignments=(t.assignments||[]).filter((id:string)=>guestIds.has(id)&&w.guests.find((g:any)=>g.id===id)?.responses?.[t.event]==='yes');}for(const b of w.budget){for(const p of b.payments||[]){if(!Number.isFinite(Number(p.amount))||Number(p.amount)<0)throw new HttpError(400,'Payment amounts must be positive.');}}}
// The photo index replaces the old D1 `photos` table: one JSON list, updated with ETag checks.
export async function photoIndex():Promise<PhotoRecord[]>{return (await dataStore().get('photos',{type:'json'}))||[];}
export async function addPhoto(record:PhotoRecord,limit?:number){await mutateJSON<PhotoRecord[]>('photos',list=>{const current=list||[];if(current.some(p=>p.id===record.id))return null;if(limit!==undefined&&record.kind==='photo'&&current.filter(p=>p.kind==='photo').length>=limit)throw new HttpError(400,'This wedding has reached its 500-photo limit.');return {value:[...current,record]};});}
export async function removePhoto(id:string){await mutateJSON<PhotoRecord[]>('photos',list=>list?.some(p=>p.id===id)?{value:list.filter(p=>p.id!==id)}:null);}
