import { getCoupleUser } from './auth';
import { initialWedding, type Wedding, sections, normalizeWedding } from './model';
import { dataStore, ifUnchanged } from './store';
import { HttpError, storedRow, row, readRsvp, readRsvps, saveRsvp, mergeGuest, inBatches, RSVP_FIELDS, PLUS_ONE_FIELDS, type WeddingRow } from './records';
export * from './records';
import { fromThisSite } from './origin';
import { validateHub } from './hub';
export async function planner(req?:Request){const user=await getCoupleUser(req);if(!user)throw new HttpError(401,'Please sign in to your wedding dashboard.');let r=await row();if(!r){await dataStore().setJSON('wedding',{owner:'couple',revision:0,w:initialWedding()},{onlyIfNew:true});r=await row();}if(!r)throw new HttpError(503,'Wedding storage is temporarily unavailable. Please try again.');if(r.owner!=='couple')throw new HttpError(503,'Import this wedding using the transfer tool before opening the planner.');return {r,user,w:r.w,owner:r.owner===user.userId};}
export async function guest(token:string){if(!token||token.length>100)throw new HttpError(403,'This invitation link is not valid.');const r=await storedRow();if(!r)throw new HttpError(404,'The invitation is not ready yet.');const w=r.w;const stored=w.guests.find(g=>g.token===token);if(!stored)throw new HttpError(403,'This invitation link is not valid. Please ask the couple for your link.');return {r,w,g:mergeGuest(stored,await readRsvp(stored.id))};}
// Saves the couple's edits. A reply a guest sent after the dashboard loaded is kept; RSVP fields the
// couple changed themselves (same rsvpVersion as loaded) become that guest's current reply.
export async function update(r:WeddingRow,w:Wedding){
 const current=await readRsvps(w.guests);
 await inBatches(w.guests,25,async g=>{const rsvp=current.get(g.id);if(!rsvp||g.rsvpVersion!==rsvp.version)return;const fields=Object.fromEntries(RSVP_FIELDS.filter(k=>g[k]!==undefined).map(k=>[k,g[k]]));if(JSON.stringify(fields)!==JSON.stringify(Object.fromEntries(RSVP_FIELDS.filter(k=>rsvp.fields[k]!==undefined).map(k=>[k,rsvp.fields[k]]))))await saveRsvp(g.id,fields);});
 const stored={...w,guests:w.guests.map(({rsvpVersion:_,...g})=>g)};
 const result=await dataStore().setJSON('wedding',{owner:r.owner,revision:r.revision+1,w:stored},ifUnchanged(r.etag));if(!result.modified)throw new HttpError(409,'Someone else just updated the wedding. Reload before saving again.');return r.revision+1;}
export function failure(e:unknown){console.error(e);return Response.json({error:e instanceof Error?e.message:'Unable to save. Please try again.'},{status:e instanceof HttpError?e.status:503});}
export function checkOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&!fromThisSite(req,origin))throw new HttpError(403,'Invalid request origin.');}
export function validate(w:any):asserts w is Wedding {if(!w||typeof w.settings!=='object')throw new HttpError(400,'Invalid wedding details.');normalizeWedding(w);for(const key of sections.slice(1)){if(!Array.isArray(w[key])||w[key].length>5000)throw new HttpError(400,'Invalid wedding records.');for(const item of w[key]){if(typeof item.id!=='string')throw new HttpError(400,'Each record needs an identifier.');}}for(const g of w.guests){if(typeof g.name!=='string'||!g.name.trim()||typeof g.token!=='string'||g.token.length<20)throw new HttpError(400,'Each guest needs a name and a secure invitation link.');}for(const g of w.guests){delete g.email;delete g.plusOneEmail;if(!g.plusOneAllowed){for(const key of PLUS_ONE_FIELDS)g[key]='';}}const guestIds=new Set(w.guests.map((g:any)=>g.id));if(guestIds.size!==w.guests.length||new Set(w.guests.map((g:any)=>g.token)).size!==w.guests.length)throw new HttpError(400,'Guest identifiers must be unique.');for(const t of w.tables){if(!Number.isInteger(Number(t.capacity))||Number(t.capacity)<1)throw new HttpError(400,'Table capacities must be positive.');t.assignments=(t.assignments||[]).filter((id:string)=>guestIds.has(id)&&w.guests.find((g:any)=>g.id===id)?.responses?.[t.event]==='yes');}for(const b of w.budget){for(const p of b.payments||[]){if(!Number.isFinite(Number(p.amount))||Number(p.amount)<0)throw new HttpError(400,'Payment amounts must be positive.');}}const hubError=validateHub(w);if(hubError)throw new HttpError(400,hubError);}
