const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const {harness}=require('./harness.cjs');
const blobs=[],links=[],elements=[];const element=()=>({style:{},append(...x){elements.push(...x)},remove(){}});
const w={settings:{video:'/api/media/video-id',music:'/api/media/music-id'},moodboard:[{image:'/api/media/private-id'}],guests:[{name:'Guest',token:'private-token'}],events:[],tables:[],budget:[],vendors:[],tasks:[],story:[],gifts:[],layout:[]};
const contents={'video-id':[0,1,2,3,4,5,6],'music-id':[3,4],'private-id':[5],'gallery-id':[6,7]};
// Behaves like the Netlify edition: answers byte ranges with at most 2 bytes per response.
const fetch=async(path,init={})=>{if(path==='/api/wedding')return Response.json({w});if(path==='/api/photos')return Response.json({photos:[{id:'gallery-id',name:'Guest',mime:'image/png',created:'2026-10-05'}]});const id=path.split('/').pop();if(!(id in contents))return new Response('',{status:404});const type=id==='video-id'?'video/mp4':id==='music-id'?'audio/mpeg':'image/png',all=contents[id];const range=/bytes=(\d+)-/.exec(new Headers(init.headers).get('range')||'');if(!range)return new Response(new Uint8Array(all),{headers:{'Content-Type':type}});const start=Number(range[1]);if(start>=all.length)return new Response(null,{status:416});const end=Math.min(all.length-1,start+1);return new Response(new Uint8Array(all.slice(start,end+1)),{status:206,headers:{'Content-Type':type,'Content-Range':`bytes ${start}-${end}/${all.length}`}});};
const sandbox={Blob,Uint8Array,DataView,TextEncoder,Map,Date,Object,Error,Number,document:{createElement(type){const e=element();if(type==='a')links.push(e);return e;},body:element()},URL:{createObjectURL(blob){blobs.push(blob);return 'blob:'+blobs.length;}},alert(message){throw Error(message);},fetch};
(async()=>{await vm.runInNewContext(fs.readFileSync('scripts/export-current-wedding.js','utf8'),sandbox);assert.equal(links.length,2);
 const {readZip,readManifest}=harness().load('lib/transfer.ts');const entries=new Map();for(const blob of blobs)readZip(new Uint8Array(await blob.arrayBuffer()),entries);
 const manifest=readManifest(entries);assert.equal(manifest.format,'our-wedding-transfer-v1');assert.equal(manifest.photos.length,4);assert.equal(manifest.photos.find(p=>p.id==='private-id').kind,'asset');assert.equal(manifest.photos.find(p=>p.id==='gallery-id').kind,'photo');assert.equal(manifest.photos.find(p=>p.id==='video-id').mime,'video/mp4');assert.equal(manifest.w.guests[0].token,'private-token');
 for(const [id,bytes]of Object.entries(contents))assert.deepEqual([...entries.get('media/'+id)],bytes);
 console.log('PASS: export tool downloads ranged media and its ZIPs pass the transfer importer checks (wedding data, guest tokens, video/music, private inspiration, gallery bytes).');})().catch(e=>{console.error(e);process.exitCode=1});
